// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EventLoop(arg1) {
  return window['go']['player']['Player']['EventLoop'](arg1);
}

export function GetImage(arg1) {
  return window['go']['player']['Player']['GetImage'](arg1);
}

export function GetMetadata() {
  return window['go']['player']['Player']['GetMetadata']();
}

export function GetPosition() {
  return window['go']['player']['Player']['GetPosition']();
}

export function GetStatus() {
  return window['go']['player']['Player']['GetStatus']();
}

export function LoadMusic(arg1, arg2) {
  return window['go']['player']['Player']['LoadMusic'](arg1, arg2);
}

export function OnShutdown() {
  return window['go']['player']['Player']['OnShutdown']();
}

export function SetPlayerStats(arg1) {
  return window['go']['player']['Player']['SetPlayerStats'](arg1);
}

export function SetPosition(arg1) {
  return window['go']['player']['Player']['SetPosition'](arg1);
}

export function SetSpeed(arg1) {
  return window['go']['player']['Player']['SetSpeed'](arg1);
}

export function SetVolume(arg1) {
  return window['go']['player']['Player']['SetVolume'](arg1);
}

export function StartUp(arg1) {
  return window['go']['player']['Player']['StartUp'](arg1);
}

export function ToggleMute() {
  return window['go']['player']['Player']['ToggleMute']();
}

export function TogglePlay() {
  return window['go']['player']['Player']['TogglePlay']();
}
