// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sharedTypes} from '../models';
import {player} from '../models';
import {context} from '../models';

export function EventLoop(arg1:any):Promise<void>;

export function GetImage(arg1:string):Promise<sharedTypes.ReturnType>;

export function GetMetadata():Promise<sharedTypes.ReturnType>;

export function GetPosition():Promise<sharedTypes.ReturnType>;

export function GetStatus():Promise<sharedTypes.ReturnType>;

export function LoadMusic(arg1:string,arg2:boolean):Promise<sharedTypes.ReturnType>;

export function OnShutdown():Promise<void>;

export function SetPlayerStats(arg1:player.PlayerStatus):Promise<sharedTypes.ReturnType>;

export function SetPosition(arg1:number):Promise<sharedTypes.ReturnType>;

export function SetSpeed(arg1:number):Promise<sharedTypes.ReturnType>;

export function SetVolume(arg1:number):Promise<sharedTypes.ReturnType>;

export function StartUp(arg1:context.Context):Promise<void>;

export function ToggleMute():Promise<sharedTypes.ReturnType>;

export function TogglePlay():Promise<sharedTypes.ReturnType>;
